{% extends "classifieds/class-base2.phtml" %}
<!-- Only variable necessary is 'ad' -->
{% block raw-javascript %}
// not in use currently
function subForm() {
  var subject = document.getElementById('em-subject');
  var title = "{{ad.title}}";
  var title_array = title.split(" ");
  for (var i = 0; i < title_array.length; i++) {
    if (i !== 0) {subject.value += "_";}
    subject.value += title_array[i];
  }

  var ferm = document.getElementById('form-email');
  ferm.submit()

}

{% endblock %}

{% block on-load %}
{{block.super}}
  var newCommentBox = document.getElementById('id_body');
  newCommentBox.className = "form-control";
  newCommentBox.placeholder = "Write your message here....";
{% endblock %}

{% block content %}
{{block.super}}



<div class="row">
  <div class="col-md-4 col-sm-4">
    <h1>
     {{ad.title}}
      <span class="text-muted">
        (#{{ad.id}})
      </span>
    </h1>
    {% if ad.creator == user %}
      <form action="/webapps/classifieds/edit/{{ad.id}}/">

        <button class="btn btn-primary btn-sm"
                type="submit">

          <span class="glyphicon glyphicon-edit"></span>&nbsp;
          Edit
        </button>
      </form>
      <form action="/webapps/classifieds/delete/{{ad.id}}/">

        <button class="btn btn-primary btn-sm"
                type="submit">

          <span class="glyphicon glyphicon-remove"></span>&nbsp;
          Delete
        </button>
      </form>
      {% endif %}

   <!-- if request.user in ad.approved -->
   {% if is_accepted %}
   <p><span class="text-muted">Reed e-mail Address:</span> {{ad.creator.username}}@reed.edu </p>
   <form action="mailto:{{ad.creator_email}}" method="GET" id="form-email">
   <input name="subject" type="hidden" value="[SINEPOSTS]&nbsp;Re:&nbsp;Post&nbsp;{{ad.id}} - {{ad.title}}" id="em-subject" />
        <button class="btn btn-block btn-primary btn-sm" type="submit">
          <span class="glyphicon glyphicon-send"></span>&nbsp;
          Email Author
	  </button>
      </form>
   {% endif %}
   <!-- show 'email author' button -->
  </div>
  <div class="col-md-8 col-sm-8">
  <br />
    <div class="well well-lg">
      <p>{{ad.text|linebreaks}}</p>
    </div> <!-- /.well -->
  </div> <!-- /.col-md-7 -->
</div> <!-- /.row -->

{% if ad.creator == user %}
   <hr class="featurette-divider">	
   <div class="container">
   {% for message in relevant_messages %}
   <div class="row">
   <div class="col-md-5">
     <div class="alert alert-info">
     	  <p>Someone wants your contact info!</p>
     	  <form action="/webapps/classifieds/accept/{{message.id}}/">
     	  	<button type="submit" class="btn btn-default btn-lg btn-block">
	  	<span class="glyphicon glyphicon-ok"></span>Accept
		</button>
     	  </form>
     	  <form action="/webapps/classifieds/reject/{{message.id}}/">
     	  	<button type="submit" class="btn btn-default btn-lg btn-block">
	  	<span class="glyphicon glyphicon-remove"></span>Reject
		</button>
          </form>
     </div>
   </div> <!-- /.row-md-5 -->
     <div class="col-md-7">
     	 <p> They've left you a message. </p>
     	 <div class="well" style="background-color: rgba(100,4,7,.25)">
     	 <p>{{ message.body }}</p>
     	 </div>
      </div> <!-- /.col-md-7 -->
  </div> <!-- /.row -->
   {% endfor %} 
   </div> <!-- /.containter -->
 
<!-- OOf, this styling is horrendous!!!! -->
{% else %}
<!-- if not_creator -->
     {% if not already_sent %}
<div class="row">
<div class="col-md-7">
<div class="well" id="new_comment">
  <form action="" method="post">
    {{form.body.errors}}
    <label for="id_body" class="sr-only">Include a little message if you'd like.</label>
    {{form.body}}
  <br>
  <button class="btn btn-primary btn-block" type="submit" value="submit">
    <span class="glyphicon glyphicon-send"></span>&nbsp;
    Request Contact Info
  </button>
  </form>
</div>
</div>
</div>
     {% endif %}
<!-- endif -->
{% endif %}
<hr class="featurette-divider">	
{% include "classifieds/includes/classif-nav.phtml" %}
<hr class="featurette-divider">
{% endblock %}