{% extends "organizations/organizations-base.phtml" %}

{% block javascript %}
<script type="text/javascript" language="JavaScript" src="/js/webapps/organizations/submit.js"></script>
{% endblock %}

{% block stylesheets %}
{{ block.super }}
<link rel="stylesheet" href="/css/webapps/object-detail-style.css" />
<link rel="stylesheet" type="text/css" href="/css/webapps/organizations/my-organizations-style.css" />
{% endblock %}

{% block content %}
{{block.super}}
<h2 class="featurette-header">Manage Your Current Organizations</h2>
{% if signator %}
<form method="get" action="/webapps/organizations/my_organizations/edit/">
<input class="btn btn-default" type="submit" value="Create a New Organization &raquo;"/>
</form>
{% endif %}
<hr class="featurette-divider">

{% for o in organizations %}

<fieldset>
<legend>{{ o.name }}</legend>

<div class="row">
  <div class="col-md-5 col-sm-5">
    <h2 class="featurette-heading">
      {{o.name}}
      <span class="text-muted">({{o.signator.get_full_name}})</span>
    </h2>
    <p class="lead"><span class="glyphicon glyphicon-info-sign"></span>&nbsp;{{o.description}}</p>
  </div>
  <div class="col-md-5 col-sm-5">
    <div class="table-responsive">
      <table class="table table-hover">
        <tr><td>Signator</td><td>{{o.signator.get_full_name}}</td></tr>
        <tr><td>Email</td><td>{{o.email}}</td></tr>
        <tr><td>Location</td><td>{{o.location}}</td></tr>
        <tr><td>Phone</td><td>{{o.phone_number}}</td></tr>
        <tr><td>Website</td><td>{{o.website}}</td></tr>
      </table>
    </div>
  </div>

  <div class="col-md-2 col-sm-2">

    <button type="button" class="btn btn-default btn-block btn-sm" disabled="disabled">
      Options<b class="caret"></b>
    </button>

     
      <form method="get" 
            action="/webapps/organization-manager/orgs/{{ o.id }}/edit/" 
  	    onsubmit="add_data_to_form(this,{{ o.id }});">
       <input class="btn btn-primary btn-sm btn-block" type="submit" value="Edit"/>
      </form>
     
    
    <form method="post" 
          action="/webapps/organization-manager/orgs/{{ o.id }}/delete/" 
  	  onsubmit="return delete_alert('{{ o.name }}');">
     <input class="btn btn-primary btn-sm btn-block" type="submit" value="Delete"></input>
    </form>
    
    
    <form method="post" 
          action="/webapps/organization-manager/orgs/{{ o.id }}/renew/">
     <input class="btn btn-primary btn-sm btn-block" type="submit" value="Renew"/>
    </form>
    
    
    <form method="get" 
          action="/webapps/organization-manager/orgs/{{ o.id }}/change-signator/">
     <input class="btn btn-primary btn-sm btn-block" type="submit" value="Change Signator"/>
    </form>
    
  </div> <!-- /.col-md-2 .col-sm-2 -->
</div>

<div class="organization-block">

<div class="object-div">
  <div class="object-div-title">
  Name:
  </div>
  <div class="object-div-content">
  {{ o.name }}
  </div>
</div>


<div class="object-div">
  <div class="object-div-title">
  Signator:
  </div>
  <div class="object-div-content">
  {{ o.signator.get_full_name }}
  </div>
</div>


<div class="object-div">
  <div class="object-div-title">
  Email:
  </div>
  <div class="object-div-content">
  {{ o.email }}
  </div>
</div>


<div class="object-div">
  <div class="object-div-title">
  Location:
  </div>
  <div class="object-div-content">
  {{ o.location }}
  </div>
</div>


<div class="object-div">
  <div class="object-div-title">
  Ph. No.:
  </div>
  <div class="object-div-content">
  {{ o.phone_number }}
  </div>
</div>


<div class="object-div">
  <div class="object-div-title">
  Website:
  </div>
  <div class="object-div-content">
  {{ o.website }}
  </div>
</div>


<div class="object-div">
  <div class="object-div-textarea-title">
  Description:
  </div>
  <div class="object-div-textarea-content">
  {{ o.description }}
  </div>
</div>

<div class="object-div">
  <div class="object-div-button">
  <form method="get" action="/webapps/organization-manager/orgs/{{ o.id }}/edit/" onsubmit="add_data_to_form(this,{{ o.id }});">
  <input class="btn btn-primary btn-sm" type="submit" value="Edit"/>
  </form>
  </div>

  <div class="object-div-button">
  <form method="post" action="/webapps/organization-manager/orgs/{{ o.id }}/delete/" onsubmit="return delete_alert('{{ o.name }}');">
  <input class="btn btn-primary btn-sm" type="submit" value="Delete"></input>
  </form>
  </div>

  <div class="object-div-button">
  <form method="post" action="/webapps/organization-manager/orgs/{{ o.id }}/renew/">
  <input class="btn btn-primary btn-sm" type="submit" value="Renew"/>
  </form>
  </div>

  <div class="object-div-button">
  <form method="get" action="/webapps/organization-manager/orgs/{{ o.id }}/change-signator/">
  <input class="btn btn-primary btn-sm" type="submit" value="Change Signator"/>
  </form>
  </div>
</div>
</fieldset>
{% endfor %}

{% if signator %}
<form method="get" action="/webapps/organizations/my_organizations/edit/">
<input class="btn btn-primary btn-lg" type="submit" value="Create a New Organization &raquo;"/>
</form>
{% endif %}
{% endblock %}
