{% extends "base.phtml" %}

{% block javascript %}
<script type="text/javascript">
function fakeLinkHover(row, focused) {
	if (focused) {
		rows = document.getElementsByTagName('tr');
		for (i = 0; i < rows.length; i++) {
			rows[i].style.backgroundColor = '';
		}
		row.style.backgroundColor = '#C45E5B';
		row.style.cursor = 'hand';
	} else {
		row.style.backgroundColor = '';
		row.style.cursor = 'pointer';
	}
};
</script>
{% endblock %}

{% block html-title %}Sin Organization Manager{% endblock %}

{% block header-title %}Sin Organization Manager{% endblock %}

{% block sidebar %}


<div class="app-body-sidebar-link-container">
  <a href="/webapps/organization-manager/orgs/html-list" class="app-body-sidebar-link">View Organizations</a>
</div>
<div class="app-body-sidebar-link-container">
  <a href="/webapps/organization-manager/my-organizations" class="app-body-sidebar-link">My Organizations</a>
</div>

{% endblock %}
