{% extends "classifieds/class-base2.phtml" %}

{% block raw-javascript %}
// not in use currently
function subForm() {
  var subject = document.getElementById('em-subject');
  var title = "{{ad.title}}";
  var title_array = title.split(" ");
  for (var i = 0; i < title_array.length; i++) {
    if (i !== 0) {subject.value += "_";}
    subject.value += title_array[i];
  }

  var ferm = document.getElementById('form-email');
  ferm.submit()

}

{% endblock %}

{% block on-load %}
{{block.super}}
  var newCommentBox = document.getElementById('id_text');
  newCommentBox.className = "form-control";
  newCommentBox.placeholder = "Please, enter your comment here...";
{% endblock %}

<!-- Only variable necessary is 'ad' -->
{% block content %}
{{block.super}}

<div class="row">
  <div class="col-md-5 col-sm-5">
    <h1>
     {{ad.title}}
    </h1>
    <p class="lead">
      <span class="text-muted">
        ({{ad.creator}}){% if ad.timestamp_time %} at {{ad.timestamp_time}}{% endif %}
      </span>
    </p>
    <a href="#new_comment">
    <button class="btn btn-primary btn-sm">
      <span class="glyphicon glyphicon-comment"></span>&nbsp;
      Comment
    </button>
    </a>
    {% if ad.creator == request.user or ismod %}
      <form action="/webapps/classifieds/edit/{{ad.id}}/">

        <button class="btn btn-primary btn-sm"
                type="submit">

          <span class="glyphicon glyphicon-edit"></span>&nbsp;
          Edit
        </button>
      </form>
      <form action="/webapps/classifieds/delete/{{ad.id}}/">
        <button class="btn btn-primary btn-sm" type="submit">
	  <span class="glyphicon glyphicon-remove"></span>
	  Delete
	</button>
      </form>  
    {% else %}
      <form action="mailto:{{ad.creator_email}}" method="GET" id="form-email">
        <input name="subject" type="hidden" value="[SINEPOSTS]&nbsp;Re:&nbsp;Post&nbsp;{{ad.id}} - {{ad.title}}" id="em-subject" />
        <button class="btn btn-primary btn-sm" type="submit">
          <span class="glyphicon glyphicon-send"></span>&nbsp;
          Email Post Author
        </button>
      </form>      
    {% endif %}
   
  </div> <!-- /.col-md-5 ... -->
  <div class="col-md-7 col-sm-7">
    <br />
    <div class="well well-lg">
      {{ad.text|linebreaks}}
    </div> <!-- /.well -->
  </div>
</div> <!-- /.row -->

<hr class="featurette-divider">
<div class="row">
  <div class="col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-1">
    <h3 class="featurette-heading">
      <span class="glyphicon glyphicon-comment"></span>&nbsp;
      Comments
      <span class="text-muted"><small>Keep it civil</small></span>
    </h3>
    {% for comment in comments reversed %}  
    <div class="well well-comment">
     <div class="row">
       <div class="col-sm-10">
         <p style="color: grey;">
           {{comment.commenter}} at {{comment.timestamp_time}} on {{comment.timestamp}}.
         </p>
         <p>{{comment.text}}</p>
       </div>
       <div class="col-sm-2"> 
         {% if comment.commenter == request.user or ismod %}
         <form action="/webapps/classifieds/cdelete/{{comment.id}}/">
           <button class="btn btn-primary btn-sm" type="submit">
	  <span class="glyphicon glyphicon-remove"></span>
	</button>
      </form>  
      {% endif %}
      </div> <!-- /.col-sm-2 -->
     </div> <!-- /.row -->
    </div>
    {% endfor %}

    <div class="well" id="new_comment">
      <form action="" method="post">
	  {{form.text.errors}}
	  <label for="id_text" class="sr-only">Text</label>      
          {{form.text}}
	<br>
	<button class="btn btn-primary btn-block" type="submit" value="submit">
	  <span class="glyphicon glyphicon-plus"></span>&nbsp;
	  Post Comment
	</button>	
      </form>
    </div>           
  </div> <!-- /.col-md-7 ... .col-md-offset-5 --> 
</div> <!-- /.row -->

{% include "classifieds/includes/classif-nav.phtml" %}

{% endblock %}
