   <center>
     <div class="btn-group">

         <button type="button" class="btn btn-classifieds"
                 onclick="javascript:document.location='/webapps/classifieds/we_almost_boned';">
            <span class="glyphicon glyphicon-heart-empty"></span>&nbsp;
              Missed Connections
         </button>

         <button type="button" class="btn btn-classifieds"
                 onclick="javascript:document.location='/webapps/classifieds/trade';">

             <span class="glyphicon glyphicon-transfer"></span>&nbsp;
               Trade
        </button>

        <button type="button" class="btn btn-classifieds"
                onclick="javascript:document.location='/webapps/classifieds/lost_found';">
          <span class="glyphicon glyphicon-question-sign"></span>&nbsp;
            Lost & Found
        </button>
        <button type="button" class="btn btn-classifieds"
                onclick="javascript:document.location='/webapps/classifieds/happenin';">
          <span class="glyphicon glyphicon-calendar"></span>&nbsp;
            Things Happenin'
        </button>
        <button type="button" class="btn btn-classifieds"
                onclick="javascript:document.location='/webapps/classifieds/ramblings';">
          <span class="glyphicon glyphicon-bullhorn"></span>&nbsp;
            Ramblings
        </button>
        <button type="button" class="btn btn-classifieds"
                onclick="javascript:document.location='https://reed.switchboardhq.com/';">
          <span class="glyphicon glyphicon-tree-deciduous"></span>&nbsp;
            Switchboardhq
        </button>
</div> <!-- /.btn-group -->
   </center>