{% extends "errors/errors-base.phtml" %}

{% block title %}Unsupported Browser!{% endblock %}
{% block h1 %}Unsupported Browser!{% endblock %}

{% block content %}
Sorry, Internet Explorer is not supported on SIN. Please download a modern browser, such as <a href="http://mozilla.com/firefox/">Firefox</a>,  <a href="http://www.apple.com/safari/">Safari</a>, or <a href="http://www.google.com/chrome">Chrome</a>.
{% endblock %}
