{% extends "finance/finance-base.phtml" %}

{% block content %}

<p class="app-body-content-greeting-paragraph">
Welcome to the Finance Committee Web Application.

<p>For more information about the members of Finance Committee, procedures, forms, etc, please visit the <a href="/wiki/senate/Funding">Finance Committee Page on the Senate Wiki</a>.</p>

There you will find such information as:
<ul>
<li>Who the head treasurer is: <a href="/senate/Funding#bigmoney">BIG MONEY</a></li>
<li>When is Finance Committee meeting this week: <a href="/senate/Funding#moneytime">MONEY TIME</a></li>
<li>Contacting the Head Treasurer: <a href="/senate/Funding#bigmoney">EMAIL BIG MONEY</a></li>
</ul>
</p>

<p>
Get Funded!
</p>

{% endblock %}
