{% extends "fundingpoll/fundingpoll-base.phtml" %}

{% load fundingpoll_tags %}

{% block src-javascript %}
{{block.super}}
<!-- used to be jquery here  -->
<script type="text/javascript" language="JavaScript" src="/js/json2_min.js"></script>
<script type="text/javascript" language="JavaScript" src="/js/webapps/fundingpoll/my_registration.js"></script>
{% endblock %}

{% block stylesheets %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="/css/webapps/object-detail-style.css"/>
<!--<link rel="stylesheet" type="text/css" href="/css/webapps/fundingpoll/my_registrations.css"/>-->
{% endblock %}

{% block content %}
{{block.super}}
<!--<div class="alert alert-danger" style="text-align:center;"><strong>Heads up!</strong> You have to Stage your group, then Save it.
 
</div> -->

  <div class="row">
    <div class="col-sm-3 col-md-3">
      <h2 class="featurette-heading">
        Register an Organization
      </h2>
      <p class="lead">
      <span class="text-muted">
        Pro-tip:
      </span>
        It's easiest to write your blurb
	in a text editor and then paste it into the form.
      </p> 
    </div>
    <div class="col-sm-9 col-md-9">
      <div class="table-responsive">
      <form role="form" id="test"> 
        <table class="table">
	  <tr>
	  <td> 
	    <label for="org-name-select">Unregistered Organization</label>
	    <select class="form-control" name="organization_name" id="org-name-select">
	    {% for o in unreg_orgs %}
	      <option id="option-{{o.id}}" value="{{o.id}}">
	        {{o.name}}
	      </option>
	    {% endfor %}
	    </select>
	  </td>
	  </tr>
	  <tr>
	  <td>
	    <label for="other_signators">Other Signators</label>
	    <input class="form-control" id="other_signators" 
                   name="other_signators" placeholder="E.g., Tobias Funke" type="text" />
          </td>
	  </tr>
	  <tr>
	  <td> 
	    <label for="comment-text-area">Funding Poll Blurb </label>
            <textarea style="height:7em;" class="form-control" name="comments" id="comment-text-area"
                      placeholder="E.g., We are a support group for never-nudes. Cutoffs welcome!"></textarea>
	  </td> <!-- move textarea inline style elsewhere -->
	  </tr>
	  <tr>
	    <td>
	    <button type="submit" class="btn btn-primary btn-block" onclick="add_row(this); return false;">
	      <h3 style="padding-top:0; margin-top:0;"> <!-- Inline as a quick hack. Move to css --> 
                <span class="glyphicon glyphicon-flash"></span>&nbsp;&nbsp;
	        You're not Done!
	      </h3>
	      <span style="font-size:smaller">(Remember to scroll down and hit "Finalize" after clicking this!)</span>
            </button>
	  </form>
	    </td>
	  </tr>
	</table>
	</form>
      </div> <!-- /.table-responsive -->
    </div> <!-- /.col-md-3 ... -->
  </div> <!-- /.row -->


<!--
<fieldset class="object-fieldset">
<legend>Register an Organization</legend>
<form onsubmit="add_row(this); return false;">
<div class="object-div">
  <div class="object-div-title">
  Unregistered Organizations:
  </div>
  <div class="object-div-content">
    <select class="object-div-input" id="org-name-select" name="organization_name">
      {% for o in unreg_orgs %}
        <option id="option-{{ o.id }}" value="{{ o.id }}">{{ o.name }}</option>
      {% endfor %}
    </select>
  </div>
</div>

<div class="object-div">
  <div class="object-div-title">
    Other Signators:
  </div>
  <div class="object-div-content">
    <input class="object-div-input" id="other_signators" name="other_signators" type="text"/>
  </div>
</div>

<div class="object-div">
  <div class="object-div-textarea-title">
    Funding Poll Blurb:
  </div>
  <div class="object-div-textarea-content" style="width: 400px;">
    <textarea class="object-div-textarea" id="comment-text-area" name="comments"></textarea>
  </div>
</div>
<div class="object-div">
<input type="submit" value="Add To List"></input>
</div>
</form>
</fieldset>
-->

<div class="row">

  <div class="col-md-12">
    <h2 class="featurette-heading">
      Current Registered Organizations
    </h2>
    <div class="table-responsive">
      <table class="table table-hover" id="org-table">
      <tbody id="org-table-body">
      <tr>
        <td colspan=5>
	  <form method="post" action="/webapps/fundingpoll/my_registrations/save/" onsubmit="add_to_form(this);">
	  <button class="btn btn-primary btn-block btn-lg" type="submit">
	    <span class="glyphicon glyphicon-ok-sign"></span>&nbsp;
	    Finalize
	    </button>
	  </form>
	</td>
      </tr>
      <tr class="table-header">
        <td> ID </td>
        <td> Name </td>
        <td> Other Signators </td>
        <td> Comments </td>
	<td> Options </td>
      </tr>
      {% for o in reg_orgs %}
      <tr>
      <td id="organization-id-{{ o.id }}">
      {{ o.organization.id }}
      </td>
      <td id="organization-name-{{ o.id }}">
       {{ o.organization.name|nbsp|safe }}
      </td>
      <td id="organization-o-sig-{{ o.id }}">
      {{ o.other_signators|nbsp|safe }}
      </td>
      <td id="organization-comment-{{ o.id }}">
      {{ o.comment|nbsp|safe }}
      </td>   
      <td>
        <form onsubmit="return false;">
	  <button type="submit" id="edit-{{o.id}}" class="btn btn-default btn-block"
	          onclick="edit_row(this);">
  	    <span class="glyphicon glyphicon-pencil"></span>
	    Edit
	  </button>
	  <button type="submit" id="delete-{{o.id}}" class="btn btn-default btn-block"
	          onclick="remove_row(this);">
            <span class="glyphicon glyphicon-remove"></span>
	    Delete
	  </button>          
        </form>
      </td>
      </tr>
      {% endfor %}
      </tbody>
      <tr>
        <td colspan=5>
	  <form method="post" action="/webapps/fundingpoll/my_registrations/save/" onsubmit="add_to_form(this);">
	  <button class="btn btn-primary btn-block btn-lg" type="submit">
	    <span class="glyphicon glyphicon-ok-sign"></span>&nbsp;
	    Finalize 
	    </button>
	  </form>
	</td>
      </tr>
      </table>
    </div>
  </div> <!-- /.col-md-12 -->
</div> <!-- /.row -->

<!--
<h3>Current Registered Organizations</h3>
<table id="org-table" border=1>
<tr>
<td>
Id
</td>
<td>
Name
</td>
<td>
Other Signators
</td>
<td>
Comments
</td>
</tr>
{% for o in reg_orgs %}
<tr>
<td id="organization-id-{{ o.id }}">
  {{ o.organization.id }}
</td>
<td id="organization-name-{{ o.id }}">
  {{ o.organization.name|nbsp|safe }}
</td>
<td id="organization-o-sig-{{ o.id }}">
  {{ o.other_signators|nbsp|safe }}
</td>
<td id="organization-comment-{{ o.id }}">
  {{ o.comment|nbsp|safe }}
</td>
<td>
<form onsubmit="return false;">
  <input type="submit" value="edit" id="edit-{{ o.id }}" onclick="edit_row(this);"></input>
  <input type="submit" value="delete" id="delete-{{ o.id }}" onclick="remove_row(this);"></input>
</form>
</td>
</tr>
{% endfor %}
</table>
<form method="post" action="/webapps/fundingpoll/my_registrations/save/" onsubmit="add_to_form(this);">
<input type="submit" value="Save List"/>
</form>
-->
{% endblock %}
