{% extends "fundingpoll/fundingpoll-base.phtml" %}

{% block content %}
{{block.super}}
Current Status: {{ status }}<br/>
Current Time: {{ time|date:"h:i:s A F d, Y" }}<br/>
<p>
Current Schedule:
<table class="table table-hover">
<tr>
<td>
Organization Registration Start: 
</td>
<td>
{{ fp.start_registration|date:"h:i:s A F d, Y" }}
</td>
</tr>
<tr>
<td>
Organization Registration End: 
</td>
<td>
{{ fp.end_registration|date:"h:i:s A F d, Y" }}
</td>
</tr>
<tr>
<td>
Voting Start: 
</td>
<td>
{{ fp.start_voting|date:"h:i:s A F d, Y" }}
</td>
</tr>
<tr>
<td>
Voting End: 
</td>
<td>
{{ fp.end_voting|date:"h:i:s A F d, Y" }}
</td>
</tr>
<tr>
<td>
Budget Submission Start: 
</td>
<td>
{{ fp.start_budgets|date:"h:i:s A F d, Y" }}
</td>
</tr>
<tr>
<td>
Budget Submission End: 
</td>
<td>
{{ fp.end_budgets|date:"h:i:s A F d, Y" }}
</td>
</tr>
</table>
</p>
{% endblock %}
