


<script type="text/javascript" language="JavaScript" src="/js/webapps/generic/onload.js"></script>
<script type="text/javascript" language="JavaScript" src="/js/jquery-1.3.2.min.js"></script>

<script>
function redirect() {
  window.location = "/webapps/fundingpoll/";
}

$(document).ready(function () {
	setTimeout("redirect()", 3000);
});
</script>


{% block content %}
Thank you for voting! Redirecting you to the Funding Poll Index in 3 seconds...
{% endblock %}
