{% extends "base.phtml" %}

{% block html-title %}SIN Forms{% endblock %}
{% block header-title %}<a href="/webapps/forms/" class="app-body-sidebar-link">SIN Forms</a>{% endblock %}

{% block sidebar %}

<div class="app-body-sidebar-link-container">
  <a href="/webapps/forms/" class="app-body-sidebar-link">View All Forms</a>
</div>
<div class="app-body-sidebar-link-container">
  <a href="/webapps/forms/my_forms/edit/" class="app-body-sidebar-link">New Form</a>
</div>
<div class="app-body-sidebar-link-container">
  <a href="/webapps/forms/my_forms/" class="app-body-sidebar-link">My Forms</a>
</div>

{% endblock %}
