{% extends "organizations/organizations-base.phtml" %}

{% block raw-javascript %}
{{block.super}}
function validate(form) {
  return true;
}

function set_action(form, id) {
  if (id != 'None') {
    form.action = '/webapps/organizations/my_organizations/save/' + id + '/';
  } else {
    form.action = '/webapps/organizations/my_organizations/save/';
  }
}

{% endblock %}

{% block stylesheets %}
{{ block.super }}
<link rel="stylesheet" href="/css/webapps/object-detail-style.css" />
<link rel="stylesheet" href="/css/webapps/organizations/organization-detail-style.css" />
{% endblock %}

{% block content %}
{{block.super}}

<form method="post" onsubmit="set_action(this,'{{ org.id }}');">
<div class="row">
  <div class="col-lg-3 col-md-4 col-sm-4">
    <h2>Create a New Organization</h2>
    <p class="lead text-muted">*denotes a required field</p>
  <div class="col-lg-3 col-md-4 col-sm-4">

    <fieldset class="object-fieldset">
    <legend>Contact Information:</legend>
    <table class="table table-hover">
      <tr>
        <td colspan=2><p class="lead">Contact Info</p></td>
      </tr>
      <tr>
        <td class="table-header">
	  *Organization Name
	</td>
	<td>
	  <input class="form-control" type="text" name="name" value="{{ org.name }}" />
	</td>
      </tr>
      <tr>
        <td class="table-header">
	  *Signator
	</td>
	<td>
	  {{user.get_full_name}}	
	</td>
      </tr>
      <tr>
        <td class="table-header">
	  *Email
	</td>
	<td>
	  <input class="form-control" type="text" name="email" value="{{ org.email }}" />	
	</td>
      </tr>
      <tr>
        <td class="table-header">
	  Location
	</td>
	<td>
	  <input class="form-control" type="text" name="location" value="{{ org.location }}" />
	</td>
      </tr>
      <tr>
        <td class="table-header">
	  Ph. No.:
	</td>
	<td>
	  <input class="form-control" type="text" name="phone_number" value="{{ org.phone_number }}" />	
	</td>
      </tr>
      <tr>
        <td class="table-header">
	  Website
	</td>
	<td>
	  <input class="form-control" type="text" name="website" value="{{ org.website }}" />
	</td>
    </table>

  </div> <!-- /.col-lg-3 .col-md-4 ... -->
  <div class="col-lg-6 col-md-4">
    <label for="org-descr">Description</label>
    <textarea class="form-control" name="description" id="org-descr">
      {{org.description}}
    </textarea>
  </div> <!-- /.col-lg-6 ... -->
</div> <!-- /.row -->

<div class="row">
  <div class="col-lg-3 col-md-3 col-sm-3">
    <p class="lead">Descriptive Information</p>
  </div> 

  <div class="col-lg-3 col-md-4 col-sm-6">
    <label for="org-meet-info">Meeting Info</label>
    <textarea class="form-control" id="org-meet-info" name="meeting_info"> 
      {{org.meeting_info}}
    </textarea>
  </div> 
  <div class="col-lg-3 col-md-4 col-sm-6">
    <label for="org-events">Annual Events</label>
    <textarea class="form-control" id="org-events" name="annual_events"> 
      {{org.annual_events}}
    </textarea>
  </div> 
  <div class="col-lg-3 col-md-4 col-sm-6">
    <label for="org-asso-org">Associated Off Campus Organizations</label>
    <textarea class="form-control" id="org-asso-org" name="associated_off_campus_organizations"> 
      {{org.associated_off_campus_organizations}}
    </textarea>
  </div> 
</div> <!-- /.row -->

<div class="row">
  <div class="col-lg-3 col-md-3 col-sm-3">

  </div>
  <div class="col-lg-4 col-md-4 col-sm-6">

  </div>
</div>

<div class="object-div">
  <div class="object-div-title">
  *Organization Name:
  </div>
  <div class="object-div-content">
  <input type="text" name="name" value="{{ org.name }}" />
  </div>
</div>

<div class="object-div">
  <div class="object-div-title">
  *Signator:
  </div>
  <div class="object-div-content" style="margin-top: 4px; margin-bottom: 2px;">
  {{ user.get_full_name }}
  </div>
</div>


<div class="object-div">
  <div class="object-div-title">
  *Email:
  </div>
  <div class="object-div-content">
  <input type="text" name="email" value="{{ org.email }}" />
  </div>
</div>


<div class="object-div">
  <div class="object-div-title">
  Location:
  </div>
  <div class="object-div-content">
  <input type="text" name="location" value="{{ org.location }}" />
  </div>
</div>


<div class="object-div">
  <div class="object-div-title">
  Ph. No.:
  </div>
  <div class="object-div-content">
  <input type="text" name="phone_number" value="{{ org.phone_number }}" />
  </div>
</div>

<div class="object-div">
  <div class="object-div-title">
  Website:
  </div>
  <div class="object-div-content">
  <input type="text" name="website" value="{{ org.website }}" />
  </div>
</div>

</fieldset>

<fieldset class="object-fieldset">
<legend>Descriptive Information</legend>

<div class="object-div">
  <div class="object-div-textarea-title">
  Description:
  </div>
  <div class="object-div-textarea-content">
  <textarea class="object-div-textarea" name="description">{{ org.description }}</textarea>
  </div>
</div>

<div class="object-div">
  <div class="object-div-textarea-title">
  Meeting Info:
  </div>
  <div class="object-div-textarea-content">
  <textarea class="object-div-textarea" name="meeting_info">{{ org.meeting_info }}</textarea>
  </div>
</div>

<div class="object-div">
  <div class="object-div-textarea-title">
  Annual Events:
  </div>
  <div class="object-div-textarea-content">
  <textarea class="object-div-textarea" name="annual_events">{{ org.annual_events }}</textarea>
  </div>
</div>

<div class="object-div">
  <div class="object-div-textarea-title">
  Associated Off Campus Organizations:
  </div>
  <div class="object-div-textarea-content">
  <textarea class="object-div-textarea" name="associated_off_campus_organizations">{{ org.associated_off_campus_organizations }}</textarea>
  </div>
</div>
</fieldset>

<fieldset class="object-fieldset">
<legend>Student Activity Information</legend>

<div class="object-div">
  <div class="object-div-textarea-title">
  Would you like your information public on reed.edu?:
  <input type="checkbox" {% if org.public_post_ok %}checked{% endif %} name="public_post_ok" />
  </div>
</div>

<p>
<div class="object-div">
  <div class="object-div-textarea-title">
  Student Activities often times gets contacted for student groups from off-campus organizations. What type of calls/emails should be forwarded to you?:
  </div>
  <div class="object-div-textarea-content">
  <textarea class="object-div-textarea" name="referral_info">{{ org.referral_info }}</textarea>
  </div>
</div>
</p>
</fieldset>

<div class="org-form-submit">
<input type="submit" value="submit">
</div>
</form>

{% endblock %}
