{% extends "base-new.phtml" %}

{% block javascript %}
<script type="text/javascript">
function fakeLinkHover(row, focused) {
	if (focused) {
		rows = document.getElementsByTagName('tr');
		for (i = 0; i < rows.length; i++) {
			rows[i].style.backgroundColor = '';
		}
		row.style.backgroundColor = '#C45E5B';
		row.style.cursor = 'hand';
	} else {
		row.style.backgroundColor = '';
		row.style.cursor = 'pointer';
	}
};
</script>
{% endblock %}

{% block html-title %}Finance Committee{% endblock %}
{% block stylesheets %} 
{{ block.super }} 
<link rel="stylesheet" type="text/css" href="/css/webapps/finance/finance-condensed.css" /> 
{% endblock %}

{% block header-title %}<a href="/webapps/finance">Finance Committee</a>{% endblock %}

{% block sidebar %}
<div><a href="/webapps/finance/view_budgets">Pending Budgets</a></div>
<div><a href="/webapps/finance/approved_budgets">Approved Budgets</a></div>
<div><a href="/webapps/finance/organization_budgets">Search Budgets</a></div>
<div><a href="/webapps/finance/submit_budget">Submit Budget</a></div>
<div><a href="/webapps/finance/my_budgets">My Budgets</a></div>
{% endblock %}
