<!DOCTYPE html>
<html>
<head>

<meta charset="utf-8">
<title>{% block html-title %}{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="SIN: The Student Information Network">
<meta name="author" content="da Webmasters">


<link rel="shortcut icon" href="/favicon.png" type="image/icon" />
<link rel="icon" href="/favicon.png" type="image/icon" />


{% block stylesheets %}
<!-- OLD STYLESHEET 
  <link rel="stylesheet" type="text/css" href="/css/webapps/app-style.css" />
-->
<link href="/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
<link href="/css/webapps/fonts.css" rel="stylehseet">
<link href="/css/webapps/booty-app-style.css" rel="stylesheet">
<link href="/css/webapps/booty-navbar-style.css" rel="stylesheet">
{% endblock %}

<style>
/* Not even sure if this is necessary */
</style>

<script src="/bootstrap/assets/js/jquery.js" type="text/javascript"></script>
<!-- lettering.js suggests putting this in the head, not at the bottom -->
<script src="/js/webapps/home/jquery.lettering-0.6.1.min.js"></script>
<script type="text/javascript">
  // Makes our big letters legit
  $(document).ready(function() {
    $("#fancy-header").lettering();
    {% block on-load %}
    {% endblock %}

  });

{% block raw-javascript %}
  function add_link() {
     var link = document.getElementById('appt');
     link.innerhtml = "Go Home"
   }

  function fix_the_last() {
    var link = document.getElementById('appt');
    link.innerHTML = "saved"
  }
{% endblock %}
</script>
{% block src-javascript %}
{% endblock %}

{% block head %}
{% endblock %}


</head>

<body {% block scroll-spy-tag %}{% endblock %}>

<!-- Begin Navbar
     ================= -->

{% include "includes/top-nav.html" %}

<!-- End Navbar
     ====================== -->



<!-- App Body
     ====================== -->

<div id="wrap">
<div id="app-body-content">
<header>
  <h1 id="fancy-header">{% block fancy-header %}SIN{% endblock %}</h1>
</header>

  <div id="app-body-inner-content">
    <div class="newLine">
      {% block content %} {% endblock %}
    </div>
  </div>
</div>
<div id="push"></div>
</div> <!-- ./wrap -->
<!--
  <div id="app-body">
    <div id="app-body-sideboard">
      <div id="app-body-inner-sideboard">
     
       <p>{{user}}<br>
       <a href="/webapps/logout">Log out</a> </p>
      </div>
    </div>
    <div id="app-body-content">
      <div id="app-body-inner-content">
  
      </div>
    </div>
  </div>
-->

<!-- End App Body
     ====================== -->



<!-- Begin Footer
     ====================== -->

<!-- The included footer uses a variable called "user"  
     I bet you can guess what that does!               -->
{% include "includes/base-footer.phtml" %}


<!-- End Footer
     ====================== -->


<!-- Placed at bottom to speed up loading of the page -->

<script src="/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- If jquery is failing for some reason:
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script> -->
<script src="/bootstrap/bootstrap-hover-dropdown.js"></script>
<script src="/bootstrap/assets/js/holder.js"></script>
<script src="/js/webapps/home/jquery.fittext.js"></script>
<script>
 jQuery("#fancy-header").fitText(2.5,{minFontSize: '10px', maxFontSize: '100 px'});
</script>
{% block extra-js %}
{% endblock %}
<script>
/*** Original nav hover dropdown animation 
     Removed because it was unintuitive
     1/29/14

$('.navbar-fixed-top .dropdown').hover(function() {

    $(this).find('.dropdown-menu',this).first().stop(true, true).slideToggle(400);

  }, function() {

      $(this).find('.dropdown-menu').first().stop(true, true).slideToggle(400);
});
 ***/

/**
  // Implements the hover-dropdown for our nav bar!
  $(document).ready(function() {
    $('.js-activated').dropdownHover().dropdown();
  });
**/

      // ADD SLIDEDOWN ANIMATION TO DROPDOWN //
      $('.dropdown').on('show.bs.dropdown', function(e){
        $(this).find('.dropdown-menu').first().stop(true, true).slideDown();
      });
      
      // ADD SLIDEUP ANIMATION TO DROPDOWN //
      $('.dropdown').on('hide.bs.dropdown', function(e){
        $(this).find('.dropdown-menu').first().stop(true, true).slideUp();
      });

</script>


</body>
</html>
