{% extends "appointments/appointments-base.phtml" %}

{% block content %}
{{block.super}}
<ul class="nav nav-pills">
  <li class="active"><a href="/webapps/appointments/open_positions/">&laquo; Back to Open Positions</a></li>
  <li class="active"><a href="/webapps/appointments/">App Com Home</a></li>
  <li class="active"><a href="/webapps/appointments/my_applications">My Applications &raquo;</a></li>
</ul>
<hr class="featurette-divider">
<h2>Your application has been received. Expect to hear back shortly! Thanks!</h2>
{% endblock %}
