{% extends "appointments/appointments-base.phtml" %}

{% block content %}
{{block.super}}

<ul class="nav nav-pills">
  <li class="active"><a href="/webapps/appointments/admin/">&laquo; Admin</a></li>
  <li class="active"><a href="/webapps/appointments/admin/create">New</a></li>
  <li class="disabled"><a href="#">Edit</li></a>
</ul>
{% if success %}
   <p class="submit-success">
     Success! You are now in editing mode. Make changes to the "{{position.name}}" position, or click New to create another position.
   </p>
{% endif %}

<hr class="featurette-divider">

<form action="" method="post" role="form">
<table class="table table-hover table-responsive">
  <tr>
  <td width=50>
    Position Name:
    </td>
    <td>
    <input type="text" class="form-control" 
           name="name" value="{{ position.name }}" /></td>
  </tr>

  <tr>
    <td>Contact:</td>
    <td>{{ user.get_full_name }}</td>
  </tr>
  <tr>
    <td>Description:</td>
    <td>
      <textarea rows=10 cols=60 
                class="form-control" name="description">{{ position.description }}</textarea>
    </td>
  </tr>
  <tr>
    <td>Expires On:</td>
    <td>
      <input type="text" class="form-control" 
             name="expires_on" value="{{ position.expires_on|date:"m-d-Y" }}"
	     placeholder="MM-DD-YYYY">
      </input>
    </td>
  </tr>
  <tr>
    <td colspan=2><button class="btn btn-primary btn-block" type="submit">Submit</button></td>
  </tr>
</table>
</form>
{% endblock %}
