{% extends "appointments/appointments-base.phtml" %}

{% block stylesheets %}
{{ block.super }}
<!--<link rel="stylesheet" type="text/css" href="/css/webapps/object-detail-style.css" />-->

<!--<link rel="stylesheet" type="text/css" href="/css/webapps/appointments/application-detail-style.css" /> -->
{% endblock %}

{% block content %}
{{block.super}}

<form method="post" action="/webapps/appointments/my_applications/edit/{{ app.id }}">

<div class="row">
<div class="col-lg-3 col-md-3 col-sm-3">
  <p class="lead"> Position Info </p>
</div>
<div class="col-lg-4 col-md-4 col-sm-4 col-lg-offset-1 col-md-offset-1 col-sm-offset-1">
  <div class="list-group">
    <a href="#" class="list-group-item">
      <h4 class="list-group-item-heading">
        Position
      </h4>
      <p class="list-group-item-text">
        {% if app %}
	  {{app.position.name}}
	{% else %}
	  {{position.name}}
	{% endif %}
      </p>
    </a>
    <a href="#" class="list-group-item">
      <h4 class="list-group-item-heading">
        Description
      </h4>
      <p class="list-group-item-text">
      {% if app %}
         {{ app.position.description }}
      {% else %}
         {{ position.description }}
      {% endif %}        
      </p>
    </a>
  </div>
</div>
<div class="col-lg-4 col-md-4 col-sm-4">
  <div class="list-group">
    <a href="#" class="list-group-item">
      <h4 class="list-group-item-heading">
        Contact
      </h4>
      <p class="list-group-item-text">
    {% if app %}
       {{ app.position.contact.get_full_name }}
    {% else %}
       {{ position.contact.get_full_name }}
    {% endif %}
      </p>
    </a>
    <a href="#" class="list-group-item">
      <h4 class="list-group-item-heading">
        Contact Email
      </h4>
      <p class="list-group-item-text">
    {% if app %}
      {{ app.position.contact.email }}
    {% else %}
      {{ position.contact.email }}
    {% endif %}
      </p>
    </a>
  </div>
</div>
</div> <!--/.row -->

<hr class="featurette-divider">

<div class="row">
<div class="col-lg-3 col-md-3 col-sm-3">
  <p class="lead">Application</p>
</div>
<div class="col-lg-8 col-md-8 col-sm-8 col-lg-offset-1 col-md-offset-1 col-sm-offset-1">
  <table class="table table-hover">
    <tr>
      <td>
        Applicant
      </td>
      <td>
        {{user.get_full_name}}
      </td>
    </tr>
    <tr>
      <td>
        Year
      </td>
      <td>
     <select class="form-control" name="year">
      <option value="Freshman"
        {% ifequal year 0 %}
        selected="true"
        {% endifequal %}
        >Freshman</option>
        <option value="Sophomore"
        {% ifequal year 1 %}
        selected="true"
        {% endifequal %}
        >Sophomore</option>
        <option value="Junior"
        {% ifequal year 2 %}
        selected="true"
        {% endifequal %}
        >Junior</option>
        <option value="Senior"
        {% ifequal year 3 %}
        selected="true"
        {% endifequal %}
        >Senior</option>
     </select>
      </td>
    </tr>
    <tr>
      <td>
        Major
      </td>
      <td>
         <input class="form-control" type="text" name="major" value="{{ app.major }}" />
      </td>
    </tr>
    <tr>
      <td>
        Preferred Pronouns (if any)
      </td>
      <td>
         <input class="form-control" type="text" name="preferred_pron" value="{{ app.preferred_pron }}" />
      </td>
    </tr>
    <tr>
      <td>
        Address
      </td>
      <td>
    <input class="form-control" type="text" name="address" value="{{ app.address }}" />
      </td>
    </tr>
    <tr>
      <td>
        Phone
      </td>
      <td>
        <input class="form-control" type="text" name="phone" value="{{ app.phone }}" />
      </td>
    </tr>
    <tr>
      <td>
        Email
      </td>
      <td>
        <input class="form-control" type="text" name="email" value="{{ app.email }}"/>
      </td>
    </tr>
  </table>
</div>
</div> <!-- /.row -->

<hr class="featurette-divider">

<div class="row">
<div class="col-lg-6 col-md-6 col-sm-6">
  <label for="sched-con">Schedule Conflicts on Sunday and Wednesday Evenings</label>
  <textarea id="sched-con" class="form-control object-div-textarea" name="schedule_conflicts">{{ app.schedule_conflicts|safe }}</textarea>
  <label for="oth-pos">Other Reed Positions</label>
  <textarea id="oth-pos" class="form-control object-div-textarea" name="other_reed_positions">{{ app.other_reed_positions|safe }}</textarea>
</div>
<div class="col-lg-6 col-md-6 col-sm-6">
  <label for="oth-em">Other Employment</label>
  <textarea id="oth-em" class="form-control object-div-textarea" name="other_employment">{{ app.other_employment|safe }}</textarea>

  <label for="exp">Experience</label>
  <textarea id ="exp" class="form-control object-div-textarea" name="experience">{{ app.experience }}</textarea>
</div>
</div> <!-- /.row -->

<div class="row">
  <div class="col-lg-4 col-md-4 col-sm-4">
    <label for="motiv">Motivation</label>
    <textarea id="motiv" class="form-control object-div-textarea" name="motivation">{{ app.motivation }}</textarea>
  </div>
  <div class="col-lg-4 col-md-4 col-sm-4">
    <label for="spec-sk">Special Skills</label>
    <textarea id="spec-sk" class="form-control object-div-textarea" name="special_skills">
      {{ app.special_skills }}</textarea>
  </div>
  <div class="col-lg-4 col-md-4 col-sm-4">
    <label for="appeal">Additional Comments</label>
    <textarea id="appeal" class="form-control object-div-textarea" name="appeal">{{ app.appeal }}</textarea>
  </div>
</div> <!-- /.row -->

<div class="row">
<div class="col-lg-12 col-md-12 col-sm-12">
<input class="btn btn-lg btn-primary btn-block" type="submit" value="Submit" />
<input class=type="text" name="position_id" style="visibility: hidden;"
{% if app %}
  value="{{ app.position.id }}"
{% else %}
  value="{{ position.id }}"
{% endif %}/>
</div>
</div>
</form>
{% endblock %}
