{% extends "appointments/appointments-base.phtml" %}

{% block content %}
  <!-- START THE FEATURETTES -->
  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7 col-sm-7">
      <h2 class="featurette-heading">
        Welcome to Appointments Committee.
        <span class="text-muted">Apply for Shit.</span></h2>
        <p class="lead">
	  Create and edit your applications for student body appointments.
	  <p>
	  <a class="btn btn-default" href="/webapps/appointments/open_positions">
            View Open Positions &raquo;
          </a>
	  <a class="btn btn-default" href="/webapps/appointments/my_applications">
            View My Applications &raquo;
          </a>
	  </p>
	</p>
        </div>
        <div class="col-md-5 col-sm-5">

        </div>
      </div>

{% endblock %}
