{% extends "appointments/appointments-base.phtml" %}

{% block content %}
{{block.super}}


    <h2>Applications <span class="text-muted">for {{position.name}}</span></h2>

    <ul class="nav nav-pills">
      <li class="active"><a href="/webapps/appointments/admin/">&laquo; Admin</a></li>
      <li class="active"><a href="/webapps/appointments/admin/edit/{{position.id}}">Edit Position Info</a></li>
    </ul>

<hr class="featurette-divider">
<table class="table table-hover">
  <tr class="table-header">
    <td>Applicant Name</td>
    <td>Action</td>
  </tr>
      {% for a in applications %}
    <tr>
    <td>{{ a.applicant.get_full_name }}</td>
    <td>
     <button class="btn btn-primary btn-block" type="submit"
            onclick="window.location = '/webapps/appointments/admin/position-{{ position.id }}/app-{{ a.id }}/';">
      <span class="glyphicon glyphicon-eye-open"></span>&nbsp; View Application
     </button>
    </td>
  </tr>
{% endfor %}
</table>

{% endblock %}
