{% extends "appointments/appointments-base.phtml" %}

{% block content %}
{{block.super}}
<table class="table table-hover">
<tr>
<td>Name:</td>
<td>{{ object.name }}</td>
</tr>
<tr>
<td>Contact:</td>
<td>{{ object.contact.get_full_name }}</td>
</tr>
<tr>
<td>Description:</td>
<td>{{ object.description }}</td>
</tr>
<tr>
<td>Expires On:</td>
<td>{{ object.expires_on|date:"h:i A F d, Y" }}</td>
</tr>
<tr>
<td>Created On:</td>
<td>{{ object.created_on|date:"h:i A F d, Y" }}</td>
</tr>
<tr>
<td>Modified On:</td>
<td>{{ object.modified_on|date:"h:i A F d, Y" }}</td>
</tr>
</table>

{% endblock %}
