{% extends "finance/finance-base.phtml" %}

{% block content %}
{{block.super}}


<button type="submit"
	class="btn btn-block btn-primary"
	onclick="javascript: document.location='/webapps/finance/submit_budget/';">
Create New Budget &raquo;
</button>

<hr class="featurette-divider">

<p class="lead"> Unapproved Budgets </p>

<form method="get" onsubmit="this.method = form_method; this.action = '/webapps/finance/my_budgets/' + form_action + '/' + budget + '/';">
<div class="table-responsive">
<table class="table table-hover">
  <tr>
    <td>
    <span class="glyphicon glyphicon-paperclip"></span>&nbsp;
     Organization
     </td>
     <td>
     <span class="glyphicon glyphicon-euro"></span>&nbsp;
        Requested
     </td>
     <td>
     <span class="glyphicon glyphicon-usd"></span>
        Allocated
     </td>
     <td>
     <span class="glyphicon glyphicon-plus-sign"></span>&nbsp;
        Created
     </td>
     <td>
     <span class="glyphicon glyphicon-edit"></span>&nbsp;
        Modified
     </td>
     <td>
     <span class="glyphicon glyphicon-cog"></span>&nbsp;
        Action
     </td>
</tr>
{% for b in unapproved_budgets %}
  <tr onclick="javascript:document.location.href = 'view_budgets/{{ b.id }}';">
     <td>
        {{ b.organization.name }}
     </td>
     <td>
        <a href="view_budgets/{{ b.id }}" class="budget-row-detailed-link">${{ b.requested }}</a>
     </td>
     <td>
        <a href="view_budgets/{{ b.id }}" class="budget-row-detailed-link">${{ b.allocated }}</a>
     </td>
     <td>
        {{ b.created_on|date:"m-d-Y" }}
     </td>
     <td>
       {{ b.modified_on|date:"m-d-Y" }}
     </td>
     <td>
       <input class="btn btn-primary btn-sm" type="submit" value="edit" onclick="budget = {{ b.id }}; form_action = 'edit'; form_method = 'get';"></input>

       <input class="btn btn-primary btn-sm" type="submit" value="delete" onclick="if(confirm('Are you sure you wish to delete this budget?')){budget = {{ b.id }}; form_action = 'delete'; form_method = 'post';return true;} return false;"></input>
     </td>
  </tr>
{% endfor %}
</table>
</div> <!-- /.table-responsive -->
</form>


<p class="lead">Approved Budgets</p>
<div class="table-responsive">
<table class="table table-hover">
  <tr>
    <td>
    <span class="glyphicon glyphicon-paperclip"></span>&nbsp;
     Organization
     </td>
     <td>
     <span class="glyphicon glyphicon-euro"></span>&nbsp;
        Requested
     </td>
     <td>
     <span class="glyphicon glyphicon-usd"></span>
        Allocated
     </td>
     <td>
     <span class="glyphicon glyphicon-plus-sign"></span>&nbsp;
        Created
     </td>
     <td>
     <span class="glyphicon glyphicon-edit"></span>&nbsp;
        Modified
     </td>
</tr>
{% for b in approved_budgets %}
  <tr onclick="javascript:document.location.href = 'view_budgets/{{ b.id }}';">
     <td>
        {{ b.organization.name }}
     </td>
     <td>
        <a href="view_budgets/{{ b.id }}" class="budget-row-detailed-link">${{ b.requested }}</a>
     </td>
     <td>
        <a href="view_budgets/{{ b.id }}" class="budget-row-detailed-link">${{ b.allocated }}</a>
     </td>
     <td>
        {{ b.created_on|date:"m-d-Y" }}
     </td>
     <td>
       {{ b.modified_on|date:"m-d-Y" }}
     </td>
  </tr>
{% endfor %}
</table>
</div> <!-- /.table-responsive -->


{% endblock %}
