{% extends "base.phtml" %}

{% block html-title %}Appointments Committee{% endblock %}
{% block header-title %}<a href="/webapps/appointments/" class="app-body-sidebar-link">Appointments Committee</a>{% endblock %}

{% block sidebar %}

<div class="app-body-sidebar-link-container">
  <a href="/webapps/appointments/open_positions" class="app-body-sidebar-link">View Open Positions</a>
</div>
<div class="app-body-sidebar-link-container">
  <a href="/webapps/appointments/my_applications" class="app-body-sidebar-link">My Applications</a>
</div>
<div class="app-body-sidebar-link-container">
  <a href="/webapps/appointments/admin/" class="app-body-sidebar-link">Appointments Manager</a>
</div>
{% endblock %}
