<!DOCTYPE html>
<html>
<head>
<!--<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-15">-->

<meta charset="utf-8">
<title>{% block html-title %}{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="SIN: The Student Information Network">
<meta name="author" content="Brett Beutell; in(re)boots">


{% block head %}{% endblock %}

{% block stylesheets %}
<!-- OLD STYLESHEET 
  <link rel="stylesheet" type="text/css" href="/css/webapps/app-style.css" />
-->
<link href="/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
<link href="/css/webapps/booty-app-style.css" rel="stylesheet">
{% endblock %}

<style>
/* Not even sure if this is necessary */
</style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>                                                           
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>                                                                               
    <![endif]-->



{% block javascript %}
{% endblock %}

</head>

<body>

<!-- Begin Navbar
     ================= -->

{% include "includes/top-nav.phtml" %}

<!-- End Navbar
     ====================== -->



<!-- App Body
     ====================== -->

<div id="app-body-content">
  <div id="app-body-inner-content">
    This should contain bootstrap headers
    With descriptions of each section
  {% block content %} {% endblock %}
  </div>
</div>
<!--
  <div id="app-body">
    <div id="app-body-sideboard">
      <div id="app-body-inner-sideboard">
     
       <p>{{user}}<br>
       <a href="/webapps/logout">Log out</a> </p>
      </div>
    </div>
    <div id="app-body-content">
      <div id="app-body-inner-content">
  
      </div>
    </div>
  </div>
-->

<!-- End App Body
     ====================== -->



<!-- Begin Footer
     ====================== -->

<!-- The included footer uses a variable called "user"  
     I bet you can guess what that does!               -->
{% include "includes/base-footer.phtml" %}


<!-- End Footer
     ====================== -->


<!-- Placed at bottom to speed up loading of the page -->
<script src="/bootstrap/assets/js/jquery.js" type="text/javascript"></script>
<script src="/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- If jquery is failing for some reason:
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script> -->

</body>
</html>
