{% extends "home/home-base.phtml" %}

{% block html-title %} The Home of SIN {% endblock %}

{% block fancy-header %}{{block.super}}⇰HOME{% endblock %}

{% block scroll-spy-tag %}
data-spy="scroll" data-target="#home-sidenav"
{% endblock %}

{% block content %} 
<hr class="featurette-divider">

<div class="container">
  <div class="row">
    <div class="col-md-3 col-sm-3">
      <div class="home-sidenav-width-hack"></div>
      <div id="home-sidenav" class="home-sidebar hidden-print affix" role="navigation" data-spy="affix">
        <ul class="nav home-sidenav">
	  <li>&nbsp;
	    <span class="glyphicon glyphicon-info-sign"></span>&nbsp;
	    <span class="text-muted">App Descriptions</span></li>
	  <li class>
	    <a href="#welcome">[ Welcome ]<a>
	  </li>
	  <li class>
	    <a href="#wiki">[ The Wiki ]</a>
	  </li>
	  <li class>
	    <a href="#appointments">[ Appointments ]</a>
	  </li>
	  <li class>
	    <a href="#orgs">[ Organizations ]</a>
	  </li>
	  <li class>
	    <a href="#fund">[ Funding Poll ]</a>
	  </li>
	  <li class>
	    <a href="#fin">[ Finance ]</a>
	  </li>
	  <li class>
	    <a href="#sinpost">[ *sinpost* ]</a>
	  </li>
	</ul>
      </div> <!-- /.home-navbar ... affix -->
    </div> <!-- /.col-md-3 -->

    <div class="col-md-9 col-sm-9" role="main">

      <div id="welcome" class="home-info-section">
        <div class="page-header"> 
          <h1> 
	    <span class="glyphicon glyphicon-star-empty"></span>&nbsp;
	    Welcome to the New SIN
	  </h1>
        </div>

	<div class="row">
	 <div class="col-md-2">
  	  <p class="lead">
	    <span class="text-muted">Let's get started.</span>
	  </p>
	  </div>
	  <div class="col-md-10">
	  <p>
	    Through a few weeks of personal hygienic neglect,
	    the Webmasters have redesigned SIN to provide you
	    with a more fluid, relevant, and responsive SIN experience.
	  </p>
	  <p>
	    If you are a SIN veteran, 
	    proceed as usual, but first 
	    <b><span style="font-size:larger;">take a gander
	    at the <i>*new*</i> sinpost app.</span>
	  </b></p>
	  <p>
	    If this is your first time on SIN, 
	    continue reading to find out about all
	    that SIN has to offer.
	  </p>
	 </div>


	</div> <!-- /.row -->
      </div>
      <div id="wiki" class="home-info-section">
        <div class="page-header">
          <h2>
	    <span class="glyphicon glyphicon-globe"></span>&nbsp;
	    The Wiki
	  </h2>
        </div>

	<div class="row">
	 <div class="col-md-5">
	  <p class="lead">
	    <span class="text-muted">
	      Read the bylaws. All of them.
	    </span>
	  </p>
	 </div>
	 <div class="col-md-7">
 	  <p><b>
	    A link to the Senate Wiki is provided under
	    "Elsewhere" on the top navigation bar.
	  </b></p>
	  <p>
	    Once there, you will find a glorious amount of
	    information pertaining to student governance.
	    Educate yourself!
	  </p>
	 </div>
	</div> <!-- /.row -->

      </div>

      <div id="appointments" class="home-info-section">
        <div class="page-header">
          <h2>
	    <span class="glyphicon glyphicon-tower"></span>&nbsp;
	    Appointments
	  </h2>
        </div>

	<div class="row">
	 <div class="col-md-5">
	  <p class="lead"><span class="text-muted">
	    Delete that rambling J-board App you wrote
	    when you were half-drunk.
	  </span></p>
	 </div>
	 <div class="col-md-7">
	  <p><b>
	    Under Appointments, you will find
	    a list of currently open Student Body Positions.
	  </b></p>
	  <p>
	    Through the Appointments Committee Web Application, 
	    you can open, edit, and complete
	    applications for said positions.
	  </p>
	 </div>
	</div> <!-- /.row -->

      </div>
      <div id="orgs" class="home-info-section">
        <div class="page-header">
          <h2>
	    <span class="glyphicon glyphicon-paperclip"></span>
	    Organization Manager
	  </h2>
        </div>

	<div class="row">
	 <div class="col-md-5">
	  <p class="lead"><span class="text-muted">
	    Delete that Kony 2012 Organization you made 
	    when you were fully-drunk.
	  </span></p>
	 </div>
	 <div class="col-md-7">
	  <p><b>
	    The Organization Manager is where you can create
	    and update the information on your student body
	    organizations. 
	  </b></p>
	  <p>
	    <i>
	    Remember, you must have attended signator training
	    to use the Organization Manager,</i>

            and our latest intelligence shows that you
            {% if user.attended_signator_training %}
              have done so ☺.
            {% else %}
              have not done so ☹.
            {% endif %}
 	  </p>
	 </div>
	</div> <!-- /.row -->

      </div>
      <div id="fund" class="home-info-section">
        <div class="page-header">
          <h2>
	    <span class="glyphicon glyphicon-stats"></span>&nbsp;
	    Funding Poll
	  </h2>
        </div>

	<div class="row">
	 <div class="col-md-5">
	  <p class="lead"><span class="text-muted">
	    Deep Six all the Ayn Rand Appreciation groups.
	  </span></p>
	 </div>
	 <div class="col-md-7">
	  <p>
	    Funding Poll is the hallmark of Student Organizational
	    Autonomy. <b>You</b> actually get a say in which groups
	    get funding for the upcoming semester. Vote wisely!
	  </p>
	 </div>
	</div> <!-- /.row -->

      </div>
      <div id="fin" class="home-info-section">
        <div class="page-header">
          <h2>
	    <span class="glyphicon glyphicon-usd"></span>&nbsp;
	    Finance Committee
	  </h2>
        </div>

	<div class="row">
	 <div class="col-md-5">
	  <p class="lead"><span class="text-muted">
	    Write <i>well-commented</i> budgets, and
	    soberly submit them to Finance Committee.
  	  </span></p>
	 </div>
	 <div class="col-md-7">
	  <p>
	    The Finance Committee Web Application allows you
	    to electronically submit budget requests.
	    <br>
	    Whether it be for pie supplies or 
	    "*<i>insert-my-musical-interest-here</i>* Ball",
	    this is where
	    you can provide a cohesive argument why you
	    deserve a slice of Student Body funds.
	  </p>
	 </div>
	</div> <!-- /.row -->

      </div>
      <div id="sinpost" class="home-info-section">
        <div class="page-header">
          <h2>
	    <span class="glyphicon glyphicon-fire"></span>&nbsp;
	    sinpost <small>*new*</small>
	  </h2>
        </div>
	<div class="row">
	 <div class="col-md-5">
  	  <p class="lead"><span class="text-muted">
	    Our private classifieds service, free from prying eyes.
	  </span></p>
	 </div>
	 <div class="col-md-7">
	  <p>
	    <b>sinpost</b> 
	    is a place to romance, buy, sell, inform, or vent.
	    <br>
	    You can anonymously submit missed connections,
	    or you can create, edit, or comment on posts in any of its
	    other sections.
	    <b>sinpost</b>, 
	    like the majority of SIN, is closed off from non-students, too,
	    so don't worry about administrative censorship (...yet).
	  </p>
	 </div>
	</div> <!-- /.row -->

      </div>
    </div> <!-- /.col-md-9 -->
  </div> <!-- /.row -->
</div>
{% endblock %}