<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
  <div id="footer"> 
    <div class="container">
      <p class="text-muted">The views expressed herein are not representative of Reed College as a whole.
       Any issues with SIN, be they technical or personal, may be forwarded to 
        <a href="mailto:sin@lists.reed.edu?Subject=SINquiry">sin@lists.reed.edu</a>.
      </p>
    </div>
  </div>
</nav>
