{% extends "base.phtml" %}

{% block html-title %}Funding Poll{% endblock %}
{% block header-title %}Funding Poll{% endblock %}

{% block sidebar %}
<div class="app-body-sidebar-link-container">
  <a href="/webapps/fundingpoll/schedule/" class="app-body-sidebar-link">Schedule</a>
</div>
<div class="app-body-sidebar-link-container">
  <a href="/webapps/fundingpoll/vote/" class="app-body-sidebar-link">Vote</a>
</div>
<div class="app-body-sidebar-link-container">
  <a href="/webapps/fundingpoll/my_registrations/" class="app-body-sidebar-link">My Organizations</a>
</div>
<div class="app-body-sidebar-link-container">
  <a href="/webapps/fundingpoll/registered/" class="app-body-sidebar-link">Registered Organizations</a>
</div>
<div class="app-body-sidebar-link-container">
  <a href="/webapps/fundingpoll/results/" class="app-body-sidebar-link">View Results</a>
</div>
{% if admin %}
<div class="app-body-sidebar-link-container">
  <a href="/webapps/fundingpoll/admin/view_budgets/" class="app-body-sidebar-link">View Budgets</a>
</div>
{% endif %}
{% endblock %}
