{% extends "finance/finance-base.phtml" %}

{% block content %}

{% if admin %}
<form method="get" action="" onsubmit="this.action = '/webapps/finance/view_budgets/respond/edit/' + budget_id;">
{% endif %}
<table class="budget-table">
  <tr class="budget-header-row">
     <td class="budget-row-signator">
     Signator
     </td>
     <td class="budget-row-organization">
     Organization
     </td>
     <td class="budget-row-requested">
        Requested
     </td>
     <td class="budget-row-allocated">
        Allocated
     </td>
     <td class="budget-row-created_on">
        Created
     </td>
     <td class="budget-row-modified_on">
        Modified
     </td>
</tr>
{% for b in budgets %}
  <tr class="budget-row {% cycle even,odd %}" onclick="javascript:location.href = 'view_budgets/{{ b.id }}';" onmouseover="fakeLinkHover(this, true)" onmouseout="fakeLinkHover(this, false)">
     <td class="budget-row-signator">
        {{ b.organization.signator.get_full_name }}
     </td>
     <td class="budget-row-organization">
        {{ b.organization.name }}
     </td>
     <td class="budget-row-requested">
        ${{ b.requested }}
     </td>
     <td class="budget-row-allocated">
        ${{ b.allocated }}
     </td>
     <td class="budget-row-created_on">
        {{ b.created_on|date:"m-d-Y" }}
     </td>
     <td class="budget-row-modified_on">
        {{ b.modified_on|date:"m-d-Y" }}
     </td>
  {% if admin %}
     <td class="budget-row-respond">
        <input type="submit" value="respond" onclick="budget_id = {{ b.id }};"></input>
     </td>
  {% endif %}
  </tr>
{% endfor %}
</table>

{% if admin %}
</form>
{% endif %}

{% endblock %}
