{% extends "finance/finance-base.phtml" %}

{% block javascript %}
{{ block.super }}
<script type="text/javascript" lang="JavaScript">
function get_first_page() {
  window.location = "/webapps/finance/approved_budgets?page=1&num={{ count }}";
}
function get_previous_page() {
  window.location = "/webapps/finance/approved_budgets?page={{ budgets.previous_page_number }}&num={{ count }}";
}
function get_next_page() {
  window.location = "/webapps/finance/approved_budgets?page={{ budgets.next_page_number }}&num={{ count }}";
}
function get_first_page() {
  window.location = "/webapps/finance/approved_budgets?page=-1&num={{ count }}";
}
</script>
{% endblock %}

{% block stylesheets %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="/css/webapps/finance/view-approved-budgets-style.css"/>
{% endblock %}

{% block content %}
<form method="get" action="/webapps/finance/approved_budgets" id="budget-nav-form">
Go to Page: <input class="approved-budget-input-size" type="text" name="page" value="{{ budgets.number }}"/>
Num per Page: <input class="approved-budget-input-size" type="text" name="num" value="{{ count }}"/>
<img src="/images/webapps/tango-icon-theme/22x22/actions/go-first.png"
onclick="get_first_page();"/>
<img src="/images/webapps/tango-icon-theme/22x22/actions/go-previous.png" onclick="get_previous_page();"/>
<img src="/images/webapps/tango-icon-theme/22x22/actions/go-next.png" onclick="get_next_page();"/>
<img src="/images/webapps/tango-icon-theme/22x22/actions/go-last.png" onclick="get_last_page();"/>
<input type="submit" value="change"/>
</form>

{% if admin %}
<form method="get" action="" onsubmit="this.action = '/webapps/finance/view_budgets/respond/edit/' + budget_id;">
{% endif %}
<table class="budget-table">
  <tr class="budget-header-row">
     <td class="budget-row-signator">
     Signator
     </td>
     <td class="budget-row-organization">
     Organization
     </td>
     <td class="budget-row-requested">
        Requested
     </td>
     <td class="budget-row-allocated">
        Allocated
     </td>
     <td class="budget-row-spent">
        Spent
     </td>
     <td class="budget-row-created_on">
        Created
     </td>
     <td class="budget-row-modified_on">
        Modified
     </td>
</tr>
{% for b in budgets.object_list %}
  <tr class="budget-row {% cycle even,odd %}" onclick="javascript:document.location.href = 'view_budgets/{{ b.id }}';" onmouseover="fakeLinkHover(this, true)" onmouseout="fakeLinkHover(this, false)">
     <td class="budget-row-signator">
        {{ b.organization.signator.get_full_name }}
     </td>
     <td class="budget-row-organization">
        {{ b.organization.name }}
     </td>
     <td class="budget-row-requested">
        ${{ b.requested }}
     </td>
     <td class="budget-row-allocated">
        ${{ b.allocated }}
     </td>
     <td class="budget-row-spent">
        ${{ b.claimed }}
     </td>
     <td class="budget-row-created_on">
        {{ b.created_on|date:"m-d-Y" }}
     </td>
     <td class="budget-row-modified_on">
        {{ b.modified_on|date:"m-d-Y" }}
     </td>
  {% if admin %}
     <td class="budget-row-respond">
        <input type="submit" value="edit response" onclick="budget_id = {{ b.id }};"></input>
     </td>
  {% endif %}
  </tr>
{% endfor %}
</table>

{% if admin %}
</form>
{% endif %}

{% endblock %}
