{% extends "finance/finance-base.phtml" %}

{% block content %}

{% if result %}
{% autoescape off %}
<p>{{ result }}</p>
{% endautoescape %}
{% endif %}

<h3>Add Signator</h3>
<form method="post" action="/webapps/finance/signator">
Username: <input type="text" name="uid" size="20"> <input type="submit" value="Add Signator">
</form>
<br>

<h3>Current Signators</h3>
<table id="user-table">
<tr>
  <td>Username</td>
  <td>Real Name</td>
  <td>Email</td>
</tr>
{% for u in currentSignators %}
  <tr>
     <td>
        {{ u.username }}
     </td>
     <td>
        {{ u.get_full_name }}
     </td>
     <td>
        {{ u.email }}
     </td>
  </tr>
{% endfor %}
</table>

{% endblock %}
